version: "3.7"
services:
  web:
    build:
      context: .
      target: builder
    user: "501:20"
    command: '/bin/bash support/docker-runserver.sh'
    volumes:
      - ./:/home/appuser:cached
    ports:
      - '8000:8000'
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - mariadbdata:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=wikiroot
      - MARIADB_USER=tracker
      - MARIADB_PASSWORD=wikipassword
      - MARIADB_DATABASE=tracker
volumes:
  mariadbdata:
    driver: local
