# Generated by Django 2.0.13 on 2019-12-18 18:23

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0071_auto_20190810_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, help_text='Optional further description of the document', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(help_text='Document filename', max_length=120, validators=[django.core.validators.RegexValidator('^[-_\\.A-Za-z0-9]+\\.[A-Za-z0-9]+$', message='We need a sane file name, such as my-invoice123.jpg')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='payload',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='deploy/tmp'), upload_to='tickets/%Y/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='fired',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fired'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('muted', 'All notifications'), ('comment', 'Comment added'), ('supervisor_notes', 'Supervisor notes changed'), ('ticket_new', 'New ticket was created'), ('ticket_delete', 'Ticket was deleted'), ('ack_add', 'Ack added'), ('ack_remove', 'Ack removed'), ('ticket_change', 'Ticket changed'), ('preexpeditures_new', 'New preexpediture was created'), ('preexpeditures_change', 'Preexpeditures changed'), ('expeditures_new', 'New expediture was created'), ('expeditures_change', 'Expeditures changed'), ('media_new', 'New media was created'), ('media_change', 'Media changed'), ('document', 'Document changed')], max_length=50, null=True, verbose_name='notification_type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(default='', verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('n_a', 'n/a'), ('unpaid', 'unpaid'), ('partially_paid', 'partially paid'), ('paid', 'paid'), ('overpaid', 'overpaid')], default='n/a', max_length=20, verbose_name='payment status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='report_url',
            field=models.CharField(blank=True, default='', help_text='URL to your report, if you want to report something (or if your report is mandatory per topic administrator).', max_length=255, verbose_name='report url'),
        ),
        migrations.AlterField(
            model_name='ticketack',
            name='ack_type',
            field=models.CharField(choices=[('user_precontent', 'presubmitted'), ('precontent', 'preaccepted'), ('user_content', 'submitted'), ('content', 'accepted'), ('user_docs', 'expense documents submitted'), ('docs', 'expense documents filed'), ('archive', 'archived'), ('close', 'closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trackerpreferences',
            name='email_language',
            field=models.CharField(choices=[('en', 'English'), ('cs', 'Czech'), ('fr', 'French'), ('ar', 'Arabic'), ('da', 'Danish'), ('fi', 'Finnish'), ('ko', 'Korean'), ('pt', 'Portuguese'), ('sv', 'Swedish'), ('zh-hant', 'Chinese-traditional')], default='cs', max_length=6, verbose_name='Email language'),
        ),
        migrations.AlterField(
            model_name='trackerpreferences',
            name='muted_ack',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ignored acks'),
        ),
        migrations.AlterField(
            model_name='trackerpreferences',
            name='muted_notifications',
            field=models.CharField(blank=True, max_length=300, verbose_name='Muted notifications'),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='ack_type',
            field=models.CharField(choices=[('user_precontent', 'presubmitted'), ('precontent', 'preaccepted'), ('user_content', 'submitted'), ('content', 'accepted'), ('user_docs', 'expense documents submitted'), ('docs', 'expense documents filed'), ('archive', 'archived'), ('close', 'closed')], max_length=50, null=True, verbose_name='ack_type'),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='notification_type',
            field=models.CharField(choices=[('muted', 'All notifications'), ('comment', 'Comment added'), ('supervisor_notes', 'Supervisor notes changed'), ('ticket_new', 'New ticket was created'), ('ticket_delete', 'Ticket was deleted'), ('ack_add', 'Ack added'), ('ack_remove', 'Ack removed'), ('ticket_change', 'Ticket changed'), ('preexpeditures_new', 'New preexpediture was created'), ('preexpeditures_change', 'Preexpeditures changed'), ('expeditures_new', 'New expediture was created'), ('expeditures_change', 'Expeditures changed'), ('media_new', 'New media was created'), ('media_change', 'Media changed'), ('document', 'Document changed')], max_length=50, verbose_name='notification_type'),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='watcher_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='watcher_type'),
        ),
    ]
