# Generated by Django 3.0.1 on 2019-12-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0072_auto_20191218_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerpreferences',
            name='email_language',
            field=models.CharField(choices=[('en', 'English'), ('cs', 'Czech'), ('fr', 'French'), ('ar', 'Arabic'), ('da', 'Danish'), ('fi', 'Finnish'), ('ko', 'Korean'), ('pt', 'Portuguese'), ('sv', 'Swedish'), ('zh-hant', 'Chinese-traditional')], default='cs', max_length=7, verbose_name='Email language'),
        ),
    ]
