# Generated by Django 3.0.1 on 2020-01-12 16:10

from django.db import migrations

def up(apps, schema_editor):
    MediaInfo = apps.get_model('tracker', 'MediaInfo')
    MediaInfoUsage = apps.get_model('tracker', 'MediaInfoUsage')
    MediaInfoCategory = apps.get_model('tracker', 'MediaInfoCategory')
    for mi in MediaInfo.objects.all():
        for usage in mi.usages:
            MediaInfoUsage.objects.create(
                mediainfo=mi,
                url=usage[0],
                title=usage[1],
                project=usage[2]
            )
        for category in mi.categories:
            MediaInfoCategory.objects.create(mediainfo=mi, title=category)

def down(apps, schema_editor):
    MediaInfo = apps.get_model('tracker', 'MediaInfo')
    MediaInfoUsage = apps.get_model('tracker', 'MediaInfoUsage')
    MediaInfoCategory = apps.get_model('tracker', 'MediaInfoCategory')

    for m in MediaInfo.objects.all():
        usages = []
        for usage in m.mediainfousage_set.all():
            usages.append([usage.url, usage.title, usage.project])
        m.usages = usages

        m.categories = [category.title for category in m.mediainfocategory_set.all()]
        m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0074_auto_20200112_1709'),
    ]

    operations = [
        migrations.RunPython(up, down)
    ]
