# Generated by Django 3.0.2 on 2020-01-21 16:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0076_auto_20200112_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediainfo',
            name='page_id',
            field=models.IntegerField(null=True, verbose_name='page id'),
        ),
        migrations.AlterField(
            model_name='document',
            name='payload',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='deploy/tmp'), upload_to='tickets/%Y/'),
        ),
    ]
