# Generated by Django 3.0.11 on 2020-12-17 18:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0077_auto_20200121_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediainfo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='name'),
        ),
    ]
