# Generated by Django 3.0.9 on 2020-12-17 18:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0078_auto_20201217_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediainfo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='mediainfo',
            unique_together={('name', 'ticket_id')},
        ),
    ]
