# Generated by Django 3.0.9 on 2021-03-04 22:27

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0079_auto_20201217_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='slug',
            field=models.SlugField(help_text='Shortcut for usage in URLs', unique=True, verbose_name='slug'),
        ),
    ]
