# Generated by Django 3.0.14 on 2022-06-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0080_auto_20210304_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerprofile',
            name='chapter_username',
            field=models.CharField(blank=True, max_length=120, verbose_name='Chapter-issued username'),
        ),
    ]
