# Generated by Django 3.0.14 on 2022-06-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0082_trackerprofile_chapter_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='ticket_comments_public',
            field=models.BooleanField(default=True, help_text='Are comments under tickets public?', verbose_name='make comments public'),
        ),
    ]
