# Generated by Django 3.0.14 on 2022-07-14 11:49

import django.core.files.storage
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0084_topic_ticket_comments_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='payload',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=settings.TRACKER_DOCS_ROOT), upload_to='tickets/%Y/'),
        ),
    ]
