# Generated by Django 3.0.14 on 2023-12-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0086_auto_20220714_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediainfo',
            old_name='canonicaltitle',
            new_name='page_title',
        ),
        migrations.AlterUniqueTogether(
            name='mediainfo',
            unique_together={('page_title', 'ticket_id')},
        ),
        migrations.RemoveField(
            model_name='mediainfo',
            name='name',
        ),
    ]
