# Generated by Django 3.0.14 on 2026-05-15 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0088_expediture_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('name', models.CharField(max_length=100, verbose_name='Account name')),
                ('prefix', models.CharField(blank=True, max_length=6, validators=[tracker.validators.validate_cnb_mod_11], verbose_name='Account prefix')),
                ('number', models.CharField(max_length=10, validators=[tracker.validators.validate_cnb_mod_11], verbose_name='Account number')),
                ('bank', models.CharField(max_length=4, validators=[tracker.validators.validate_bank_code], verbose_name='Account bank code')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='tracker.TrackerProfile', verbose_name='Account owner')),
            ],
            options={
                'verbose_name': 'Bank account',
                'verbose_name_plural': 'Bank accounts',
            },
        ),
        migrations.CreateModel(
            name='ImportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Imported at')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('order_number', models.CharField(blank=True, max_length=64, verbose_name='Order number')),
                ('error', models.BooleanField(default=False, verbose_name='error')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_symbol', models.CharField(blank=True, max_length=20, verbose_name='variable symbol')),
                ('specific_symbol', models.CharField(blank=True, max_length=20, verbose_name='specific symbol')),
                ('constant_symbol', models.CharField(blank=True, max_length=20, verbose_name='constant symbol')),
                ('account_number', models.CharField(blank=True, help_text='Or you can enter your account number manually, but do not use both.', max_length=50, validators=[tracker.validators.validate_full_bank_account], verbose_name='bank account')),
                ('saved_account', models.ForeignKey(blank=True, help_text='Choose from saved accounts.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.BankAccount', verbose_name='account link')),
            ],
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id'], 'permissions': (('import_expenditures', 'Can import all expenditures'),), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AddField(
            model_name='expediture',
            name='linked_expenditure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Expediture', verbose_name='linked expenditure'),
        ),
        migrations.AddField(
            model_name='expediture',
            name='payment_type',
            field=models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('foreign_transfer', 'International bank transfer'), ('card', 'Card'), ('cash', 'Cash'), ('internal_transfer', 'Internal transfer'), ('income', 'Income (Co-financing)')], default='bank_transfer', max_length=30, verbose_name='payment type'),
        ),
        migrations.AddField(
            model_name='grant',
            name='source_bank_account',
            field=models.CharField(blank=True, help_text='Number of the transparent account from which the funds will be disbursed', max_length=22, verbose_name='Source bank account'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('paymentinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.PaymentInfo')),
                ('template_name', models.CharField(max_length=100, verbose_name='template name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
            bases=('tracker.paymentinfo',),
        ),
        migrations.AddField(
            model_name='expediture',
            name='import_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.ImportInfo', verbose_name='import info'),
        ),
        migrations.AddField(
            model_name='expediture',
            name='payment_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.PaymentInfo', verbose_name='payment info'),
        ),
    ]
